### PR TITLE
Updated offsets for the 18i20 (Ubuntu 18.04 LTS)

### PR DESCRIPTION
**Pull request by happydebugging**
Tested on Ubuntu 18.04 with an 18i20.

### CODE REVIEW

**Comment by x42** [comment]
This will break offsets for everyone who is using vaniall Linux and is not using Ubuntu 18.04.

**Comment by x42** [comment]
PS. I don't mean to discourage you helping yourself.

It was my mistake to dump this code using numeric indices  (instead of parsing parameter names) and not anticipating that some distro would change the mixer-driver numerics index.

I don't see a way to maintain multiple different numeric offsets for different distributions or patched kernels.

Ideally the tool would be properly written and parse the offsets from the name(s). Then again looking at the dump for your system (https://github.com/x42/scarlett-mixer/issues/8#issuecomment-397781809 ) for ID 31 and 52 look like there's a bug and parsing would likewise fall over...

**Comment by happydebugging** [comment]
Hi sorry for that, it was not my intention to break other distros.  I kept the original values in the comments. I hope it did help some folks to understand how to change the offsets based on the dump they get. Many thanks for this excellent mixer, that saved a lot of time to write one from scratch. :-)

**Comment by nrobadey** [comment]
I use Debian, and for me those setting work on an 18i20:
```
                .matrix_mix_offset = 52, .matrix_mix_stride = 9,
                .matrix_in_offset = 51, .matrix_in_stride = 9,
                .input_offset = 32,
```
It seems the way to use the code is to hardcode whatever works with your config, or improve the code as suggested by x42.
By the way thanks for this nice mixer!

**Pull request closed without merging**
